export const ActionTypes = {
	// Login
	LOGIN_REQUEST: "LOGIN_REQUEST",
	LOGIN_SUCCESS: "LOGIN_SUCCESS",
	LOGIN_FAILURE: "LOGIN_FAILURE",
	UPDATE_ACCOUNT: "UPDATE_ACCOUNT",
	ADD_USER: "ADD_USER",
	// Logout
	LOGOUT_REQUEST: "LOGOUT_REQUEST",
};
