export const SolActionTypes = {
	// Login
	LOGIN_REQUEST: "SOL_LOGIN_REQUEST",
	LOGIN_SUCCESS: "SOL_LOGIN_SUCCESS",
	LOGIN_FAILURE: "SOL_LOGIN_FAILURE",
	UPDATE_ACCOUNT: "SOL_UPDATE_ACCOUNT",
	ADD_USER: "SOL_ADD_USER",
	// Logout
	LOGOUT_REQUEST: "SOL_LOGOUT_REQUEST",
};
